#!/bin/bash
# Cursor Extensions Backup
# Generated on 2026-05-07 00:45:41
# Total extensions: 50

cursor --install-extension aaron-bond.better-comments
cursor --install-extension alexdauenhauer.catppuccin-noctis-icons
cursor --install-extension anthropic.claude-code
cursor --install-extension anysphere.cursorpyright
cursor --install-extension arcticicestudio.nord-visual-studio-code
cursor --install-extension azemoh.theme-onedark
cursor --install-extension bierner.markdown-preview-github-styles
cursor --install-extension catppuccin.catppuccin-vsc
cursor --install-extension codezombiech.gitignore
cursor --install-extension davidanson.vscode-markdownlint
cursor --install-extension ecmel.vscode-html-css
cursor --install-extension enkia.tokyo-night
cursor --install-extension esbenp.prettier-vscode
cursor --install-extension evgeniypeshkov.syntax-highlighter
cursor --install-extension formulahendry.auto-rename-tag
cursor --install-extension formulahendry.code-runner
cursor --install-extension foxundermoon.shell-format
cursor --install-extension google.geminicodeassist
cursor --install-extension james-yu.latex-workshop
cursor --install-extension johnnymorganz.stylua
cursor --install-extension leojhonsong.latex-extension-pack
cursor --install-extension llvm-vs-code-extensions.vscode-clangd
cursor --install-extension ltex-plus.vscode-ltex-plus
cursor --install-extension mads-hartmann.bash-ide-vscode
cursor --install-extension mathematic.vscode-latex
cursor --install-extension mechatroner.rainbow-csv
cursor --install-extension ms-python.black-formatter
cursor --install-extension ms-python.debugpy
cursor --install-extension ms-python.isort
cursor --install-extension ms-python.pylint
cursor --install-extension ms-python.python
cursor --install-extension ms-toolsai.jupyter
cursor --install-extension ms-toolsai.jupyter-keymap
cursor --install-extension ms-toolsai.jupyter-renderers
cursor --install-extension ms-toolsai.vscode-jupyter-cell-tags
cursor --install-extension ms-toolsai.vscode-jupyter-slideshow
cursor --install-extension ms-vscode.makefile-tools
cursor --install-extension openai.chatgpt
cursor --install-extension pkief.material-product-icons
cursor --install-extension qcz.text-power-tools
cursor --install-extension redhat.vscode-yaml
cursor --install-extension rintoj.json-organizer
cursor --install-extension ritwickdey.liveserver
cursor --install-extension shakram02.bash-beautify
cursor --install-extension sumneko.lua
cursor --install-extension tal7aouy.icons
cursor --install-extension tamasfe.even-better-toml
cursor --install-extension tecosaur.latex-utilities
cursor --install-extension yzhang.dictionary-completion
cursor --install-extension yzhang.markdown-all-in-one
