ai.opencode.opencode
app.drey.KeyRack
app.drey.Warp
be.alexandervanhee.gradia
ca.desrt.dconf-editor
com.belmoussaoui.Obfuscate
com.github.fabiocolacio.marker
com.github.finefindus.eyedropper
com.github.huluti.Curtail
com.github.jeromerobert.pdfarranger
com.github.johnfactotum.Foliate
com.github.qarmin.czkawka
com.github.tchx84.Flatseal
com.google.Chrome
com.mattjakeman.ExtensionManager
com.pojtinger.felicitas.Multiplex
com.rafaelmardojai.Blanket
com.rawtherapee.RawTherapee
com.usebottles.bottles
com.vscodium.codium
dev.mufeed.Wordbook
dev.vencord.Vesktop
fr.handbrake.ghb
garden.jamie.Morphosis
io.bassi.Amberol
io.github.CyberTimon.RapidRAW
io.github.cboxdoerfer.FSearch
io.github.diegoivan.pdf_metadata_editor
io.github.dvlv.boxbuddyrs
io.github.finefindus.Hieroglyphic
io.github.flattool.Warehouse
io.github.giantpinkrobots.flatsweep
io.github.giantpinkrobots.varia
io.github.kolunmi.Bazaar
io.github.shiftey.Desktop
io.github.tobagin.karere
io.github.vikdevelop.SaveDesktop
io.gitlab.adhami3310.Converter
io.gitlab.adhami3310.Impression
io.gitlab.liferooter.TextPieces
io.gitlab.news_flash.NewsFlash
io.missioncenter.MissionCenter
it.mijorus.gearlever
md.obsidian.Obsidian
net.mediaarea.MediaInfo
net.nokyan.Resources
org.audacityteam.Audacity
org.avidemux.Avidemux
org.bunkus.mkvtoolnix-gui
org.darktable.Darktable
org.flathub.flatpak-external-data-checker
org.freefilesync.FreeFileSync
org.gnome.Lollypop
org.gnome.World.PikaBackup
org.gnome.gitlab.YaLTeR.Identity
org.gtkhash.gtkhash
org.inkscape.Inkscape
org.jabref.jabref
org.libreoffice.LibreOffice
org.localsend.localsend_app
org.lyx.LyX
org.signal.Signal
org.sqlitebrowser.sqlitebrowser
org.telegram.desktop
org.torproject.torbrowser-launcher
org.videolan.VLC
page.codeberg.libre_menu_editor.LibreMenuEditor
page.kramo.Sly
re.sonny.Junction
se.sjoerd.Graphs
top.akizip.akizip
tv.kodi.Kodi
us.zoom.Zoom
xyz.parlatype.Parlatype
