# vim:ft=kitty
## name: Nord Storm
## blurb: Nord variant with Snow Storm foreground and brighter accents.

foreground           #eceff4
background           #2e3440
selection_foreground #eceff4
selection_background #4c566a

cursor            #eceff4
cursor_text_color #2e3440

url_color #88c0d0

active_border_color   #88c0d0
inactive_border_color #3b4252
bell_border_color     #ebcb8b
visual_bell_color     none

active_tab_foreground   #2e3440
active_tab_background   #8fbcbb
inactive_tab_foreground #d8dee9
inactive_tab_background #3b4252
tab_bar_background      #2e3440
tab_bar_margin_color    none

mark1_foreground #2e3440
mark1_background #8fbcbb
mark2_foreground #2e3440
mark2_background #d08770
mark3_foreground #2e3440
mark3_background #ebcb8b

# black
color0 #3b4252
color8 #4c566a

# red
color1 #bf616a
color9 #bf616a

# green
color2  #a3be8c
color10 #a3be8c

# yellow
color3  #ebcb8b
color11 #d08770

# blue
color4  #81a1c1
color12 #5e81ac

# magenta
color5  #b48ead
color13 #b48ead

# cyan
color6  #88c0d0
color14 #8fbcbb

# white
color7  #e5e9f0
color15 #eceff4
