# Starship prompt — Nord + Dracula accents
# Palette:
#   user:     #2e3440  (Nord0)
#   dir:      #3b4252  (Nord1)
#   git:      #434c5e  (Nord2)
#   version:  #4c566a  (Nord3)
#   doc:      #5e81ac  (Nord10, close to Dracula blue)
#   time:     #6272a4  (Dracula-ish desaturated blue)

# Powerline separators and blocks:
#   We paint left-to-right segments with matching bg/fg pairs.

format = """
[░▒▓](#2e3440)\
$os\
$username\
[](bg:#3b4252 fg:#2e3440)\
$directory\
[](fg:#3b4252 bg:#434c5e)\
$git_branch\
$git_status\
[](fg:#434c5e bg:#4c566a)\
$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#4c566a bg:#5e81ac)\
$docker_context\
[](fg:#5e81ac bg:#6272a4)\
$time\
[ ](fg:#6272a4)\
\n
$cmd_duration\
$character\
"""

# Add a blank line between prompt and command output.
# add_newline = false

[line_break]
# Keep the explicit line break enabled to separate the status line and prompt line.
disabled = false

# Username block. Root color diverges from Nord by design.
[username]
show_always = true
style_user = "bg:#2e3440"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

# OS indicator off by default. Enable if we want container/WSL hints.
[os]
style = "bg:#9A348E"
disabled = true

# Directory segment. Truncate deep paths and map common folders to glyphs.
[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

# Compiler/runtime language blocks share Nord3 background.
[c]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#434c5e"   # fixed double-# typo
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

# Git block on Nord2 to sit between dir and runtimes.
[git_branch]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e"
format = '[$all_status$ahead_behind ]($style)'

# Docker context pops with Nord10.
[docker_context]
symbol = " "
style = "bg:#5e81ac"
format = '[ $symbol $context ]($style) $path'

# Clock on Dracula-ish blue.
[time]
disabled = false
time_format = "%R"        # 24h HH:MM
style = "bg:#6272a4"
format = '[  $time ]($style)'

# Prompt character. Success uses time accent. Errors in bold red.
[character]
success_symbol = '[ ➜](#6272a4)'
error_symbol   = '[ ➜](bold red)'
# style = "bg:#6272a4"

# Command duration shows for runs ≥ 500 ms.
[cmd_duration]
min_time = 500
format = ' [$duration](#6272a4)'

