general.import = ["~/.config/alacritty/themes/nordfox.toml"]

[window]
decorations = "full"
startup_mode = "Windowed"
opacity = 0.85
dynamic_padding = true

[window.padding]
x = 10
y = 10

[font]
size = 12.0

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "Bold Italic"

[cursor]
style.shape = "Block"
style.blinking = "On"
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" }
]
